name: Docker build and publish

on:
  push:
    branches:
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: battmoteam/battmogui:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u lorenah84 --password-stdin

      - name: Build and Publish
        run: |
          docker compose -f docker-compose.yml build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} && docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


         
